GET {{api_host}}//api/public/v1/businesses/EnBW

GET {{api_host}}//api/public/v1/businesses/1

GET {{api_host}}//api/public/v1/businesses?name=p&sorted_by=created&limit=0

GET {{api_host}}//api/public/v1/businesses
