### Get locations
GET {{api_host}}/api/public/v1/locations


### Get locations by lat, lon and radius
GET {{api_host}}/api/public/v1/locations?lat=48.59523&lon=8.86648&radius=1000000


### Get location by ID
GET {{api_host}}/api/public/v1/locations/1
