PROJECT_URL: 'http://localhost:5000'
SECRET_KEY: 'random-key'

SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:root@mysql/ocpdb'
CELERY_BROKER_URL: 'amqp://rabbitmq'

ADMINS: ['your-admin-email@binary-butterfly.de']
MAILS_FROM: 'your-app@binary-butterfly.de'
MAIL_USERNAME: 'your-login@binary-butterfly.de'
MAIL_PASSWORD: 'your-password'

REMOTE_SERVERS:
  STADTNAVI:
    url: 'https://api.dev.stadtnavi.eu'
  SW_STUTTGART:
    url: 'https://new-poi.chargecloud.de'

SERVER_AUTH_USERS:
  # Test user for local development
  dev:
    hash: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08  # test
    roles:
      - bnetza

AUTO_FETCH_SOURCES:
  - bnetza
  - sw-stuttgart
