PROJECT_URL: 'http://localhost:5010'
SECRET_KEY: 'random-key'
DEBUG: True

SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:root@mysql/ocpdb'
SQLALCHEMY_ENGINE_OPTIONS:
  pool_size: 100
  pool_recycle: 600
CELERY_BROKER_URL: 'amqp://rabbitmq'

OBJECT_ID_SECRET: secret

REMOTE_SERVERS:
  LADENETZ:
    url: mock://ladenetz
    user: ocpdb
    password: test
  STADTNAVI:
    url: mock://stadtnavi
  SW_STUTTGART:
    url: mock://sw-stuttgart
  CHARGEIT:
    url: mock://chargeit
    user: ocpdb
    password: test
  GIROE:
    url: mock://giro-e
    user: ocpdb
    password: test
  BNETZA:
    url: mock://bnetza
