FROM python:3.11-alpine

RUN apk update && \
    apk upgrade && \
    apk add bash

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /app
WORKDIR /app

COPY requirements.txt requirements-dev.txt .

RUN apk add geos geos-dev alpine-sdk && \
    pip install -r requirements.txt -r requirements-dev.txt && \
    apk del alpine-sdk geos-dev

EXPOSE 5000
