FROM python:3.11-alpine

RUN apk update && \
    apk upgrade && \
    apk add bash

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /app
WORKDIR /app

COPY requirements.txt requirements-dev.txt .
RUN pip install -r requirements.txt -r requirements-dev.txt

EXPOSE 5000
