[tool.ruff]
exclude = [
    "dev/*"
]

lint.select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "Q", # pydocstyle
    "I", # isort
    "T", # mypy
    "S", # flake8
    "I", # isort
]

# Sadly, this sometimes means that intentional newlines get broken. Solution would be https://github.com/astral-sh/ruff/issues/8598
line-length = 140

[tool.ruff.lint.pycodestyle]
# Hard limit at 140 characters
max-line-length = 140

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S101", "S105", "S106"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"
