"""better external reference

Revision ID: 61cd606bbc55
Revises: 6fcdaafd45ac
Create Date: 2021-12-26 10:20:30.473906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61cd606bbc55'
down_revision = '6fcdaafd45ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargepoint', sa.Column('source', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_chargepoint_source'), 'chargepoint', ['source'], unique=False)
    op.create_index('uid_source', 'chargepoint', ['uid', 'source'], unique=False)
    op.drop_column('chargepoint', 'giroe_id')
    op.add_column('connector', sa.Column('source', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_connector_source'), 'connector', ['source'], unique=False)
    op.create_index('uid_source', 'connector', ['uid', 'source'], unique=False)
    op.drop_column('connector', 'giroe_id')
    op.add_column('location', sa.Column('source', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_location_source'), 'location', ['source'], unique=False)
    op.create_index('uid_source', 'location', ['uid', 'source'], unique=False)
    op.drop_column('location', 'giroe_id')
    op.execute( "ALTER TABLE `chargepoint` CHANGE `status` `status` ENUM('AVAILABLE', 'BLOCKED', 'CHARGING', 'INOPERATIVE', 'OUTOFORDER', 'PLANNED', 'REMOVED', 'RESERVED', 'UNKNOWN', 'STATIC') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('giroe_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_index('uid_source', table_name='location')
    op.drop_index(op.f('ix_location_source'), table_name='location')
    op.drop_column('location', 'source')
    op.add_column('connector', sa.Column('giroe_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_index('uid_source', table_name='connector')
    op.drop_index(op.f('ix_connector_source'), table_name='connector')
    op.drop_column('connector', 'source')
    op.add_column('chargepoint', sa.Column('giroe_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_index('uid_source', table_name='chargepoint')
    op.drop_index(op.f('ix_chargepoint_source'), table_name='chargepoint')
    op.drop_column('chargepoint', 'source')
    op.execute("ALTER TABLE `chargepoint` CHANGE `status` `status` ENUM('AVAILABLE', 'BLOCKED', 'CHARGING', 'INOPERATIVE', 'OUTOFORDER', 'PLANNED', 'REMOVED', 'RESERVED', 'UNKNOWN') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    # ### end Alembic commands ###
