"""init

Revision ID: 6fcdaafd45ac
Revises: 
Create Date: 2021-06-06 15:15:31.328507

"""
from alembic import op
import sqlalchemy as sa
from webapp.storage.base import Point


# revision identifiers, used by Alembic.
revision = '6fcdaafd45ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('category', sa.Enum('CHARGER', 'ENTRANCE', 'LOCATION', 'NETWORK', 'OPERATOR', 'OTHER', 'OWNER', name='ImageCategory'), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('last_download', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('option',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Enum('string', 'date', 'datetime', 'integer', 'decimal', 'dict', 'list', name='OptionType'), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_index(op.f('ix_option_key'), 'option', ['key'], unique=False)
    op.create_table('business',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logo_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['logo_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('giroe_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('suboperator_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('parking_type', sa.Enum('ALONG_MOTORWAY', 'PARKING_GARAGE', 'PARKING_LOT', 'ON_DRIVEWAY', 'ON_STREET', 'UNDERGROUND_GARAGE', name='ParkingType'), nullable=True),
    sa.Column('time_zone', sa.String(length=32), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_and_conditions', sa.String(length=255), nullable=True),
    sa.Column('twentyfourseven', sa.Boolean(), nullable=True),
    sa.Column('geometry', Point(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['suboperator_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('chargepoint',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.BigInteger(), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('giroe_id', sa.BigInteger(), nullable=True),
    sa.Column('evse_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'BLOCKED', 'CHARGING', 'INOPERATIVE', 'OUTOFORDER', 'PLANNED', 'REMOVED', 'RESERVED', 'UNKNOWN', name='ChargepointStatus'), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('floor_level', sa.String(length=16), nullable=True),
    sa.Column('physical_reference', sa.String(length=255), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('parking_uid', sa.String(length=255), nullable=True),
    sa.Column('parking_floor_level', sa.String(length=255), nullable=True),
    sa.Column('parking_spot_number', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_reservation', sa.Float(), nullable=True),
    sa.Column('capabilities', sa.Integer(), nullable=True),
    sa.Column('parking_restrictions', sa.Integer(), nullable=True),
    sa.Column('terms_and_conditions', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('exceptional_period',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('opening', 'closing', name='ExceptionalPeriodType'), nullable=True),
    sa.Column('period_begin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('location_image',
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('image_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], )
    )
    op.create_table('regular_hours',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('weekday', sa.SmallInteger(), nullable=True),
    sa.Column('period_begin', sa.Integer(), nullable=True),
    sa.Column('period_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('chargepoint_image',
    sa.Column('chargepoint_id', sa.BigInteger(), nullable=True),
    sa.Column('image_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chargepoint_id'], ['chargepoint.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], )
    )
    op.create_table('connector',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chargepoint_id', sa.BigInteger(), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('giroe_id', sa.BigInteger(), nullable=True),
    sa.Column('standard', sa.Enum('CHADEMO', 'DOMESTIC_A', 'DOMESTIC_B', 'DOMESTIC_C', 'DOMESTIC_D', 'DOMESTIC_E', 'DOMESTIC_F', 'DOMESTIC_G', 'DOMESTIC_H', 'DOMESTIC_I', 'DOMESTIC_J', 'DOMESTIC_K', 'DOMESTIC_L', 'IEC_60309_2_single_16', 'IEC_60309_2_three_16', 'IEC_60309_2_three_32', 'IEC_60309_2_three_64', 'IEC_62196_T1', 'IEC_62196_T1_COMBO', 'IEC_62196_T2', 'IEC_62196_T2_COMBO', 'IEC_62196_T3A', 'IEC_62196_T3C', 'PANTOGRAPH_BOTTOM_UP', 'PANTOGRAPH_TOP_DOWN', 'TESLA_R', 'TESLA_S', name='ConnectorType'), nullable=True),
    sa.Column('format', sa.Enum('SOCKET', 'CABLE', name='ConnectorFormat'), nullable=True),
    sa.Column('power_type', sa.Enum('AC_1_PHASE', 'AC_3_PHASE', 'DC', name='PowerType'), nullable=True),
    sa.Column('max_voltage', sa.Integer(), nullable=True),
    sa.Column('max_amperage', sa.Integer(), nullable=True),
    sa.Column('max_electric_power', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_and_conditions', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['chargepoint_id'], ['chargepoint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('related_resource',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chargepoint_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('types', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chargepoint_id'], ['chargepoint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    # ### end Alembic commands ###
    op.execute("CREATE SPATIAL INDEX geometry_index ON location (geometry)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_resource')
    op.drop_table('connector')
    op.drop_table('chargepoint_image')
    op.drop_table('regular_hours')
    op.drop_table('location_image')
    op.drop_table('exceptional_period')
    op.drop_table('chargepoint')
    op.drop_table('location')
    op.drop_table('business')
    op.drop_index(op.f('ix_option_key'), table_name='option')
    op.drop_table('option')
    op.drop_table('image')
    # ### end Alembic commands ###
