"""init

Revision ID: e2268b2cf1dd
Revises: 
Create Date: 2022-12-28 17:14:18.926854

"""

import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

from webapp.models.base import Point

# revision identifiers, used by Alembic.
revision = 'e2268b2cf1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('logo_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['logo_id'], ['image.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_business_name'), 'business', ['name'], unique=False)
    op.create_table('connector',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('evse_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('standard', sa.Enum('CHADEMO', 'DOMESTIC_A', 'DOMESTIC_B', 'DOMESTIC_C', 'DOMESTIC_D', 'DOMESTIC_E', 'DOMESTIC_F', 'DOMESTIC_G', 'DOMESTIC_H', 'DOMESTIC_I', 'DOMESTIC_J', 'DOMESTIC_K', 'DOMESTIC_L', 'IEC_60309_2_single_16', 'IEC_60309_2_three_16', 'IEC_60309_2_three_32', 'IEC_60309_2_three_64', 'IEC_62196_T1', 'IEC_62196_T1_COMBO', 'IEC_62196_T2', 'IEC_62196_T2_COMBO', 'IEC_62196_T3A', 'IEC_62196_T3C', 'PANTOGRAPH_BOTTOM_UP', 'PANTOGRAPH_TOP_DOWN', 'TESLA_R', 'TESLA_S', name='connectortype'), nullable=True),
    sa.Column('format', sa.Enum('SOCKET', 'CABLE', name='connectorformat'), nullable=True),
    sa.Column('power_type', sa.Enum('AC_1_PHASE', 'AC_3_PHASE', 'DC', name='powertype'), nullable=True),
    sa.Column('max_voltage', sa.Integer(), nullable=True),
    sa.Column('max_amperage', sa.Integer(), nullable=True),
    sa.Column('max_electric_power', sa.Integer(), nullable=True),
    sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('terms_and_conditions', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['evse_id'], ['evse.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_connector_uid'), 'connector', ['uid'], unique=False)
    op.create_table('evse',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BLOCKED', 'CHARGING', 'INOPERATIVE', 'OUTOFORDER', 'PLANNED', 'REMOVED', 'RESERVED', 'UNKNOWN', 'STATIC', name='EvseStatus'), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('floor_level', sa.String(length=16), nullable=True),
    sa.Column('physical_reference', sa.String(length=255), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('parking_uid', sa.String(length=255), nullable=True),
    sa.Column('parking_floor_level', sa.String(length=255), nullable=True),
    sa.Column('parking_spot_number', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('max_reservation', sa.Float(), nullable=True),
    sa.Column('capabilities', sa.Integer(), nullable=True),
    sa.Column('parking_restrictions', sa.Integer(), nullable=True),
    sa.Column('terms_and_conditions', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_evse_uid'), 'evse', ['uid'], unique=False)
    op.create_table('evse_image',
    sa.Column('evse_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evse_id'], ['evse.id'], use_alter=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], use_alter=True)
    )
    op.create_table('exceptional_closing_period',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('period_begin', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('period_end', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('exceptional_opening_period',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('period_begin', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('period_end', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('category', sa.Enum('CHARGER', 'ENTRANCE', 'LOCATION', 'NETWORK', 'OPERATOR', 'OTHER', 'OWNER', name='imagecategory'), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('last_download', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_image_external_url'), 'image', ['external_url'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('suboperator_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('duplicate_location_id', sa.BigInteger(), nullable=True),
    sa.Column('duplicate_probability', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('parking_type', sa.Enum('ALONG_MOTORWAY', 'PARKING_GARAGE', 'PARKING_LOT', 'ON_DRIVEWAY', 'ON_STREET', 'UNDERGROUND_GARAGE', 'PRIVATE', name='parkingtype'), nullable=True),
    sa.Column('time_zone', sa.String(length=32), nullable=True),
    sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('terms_and_conditions', sa.String(length=255), nullable=True),
    sa.Column('twentyfourseven', sa.Boolean(), nullable=True),
    sa.Column('geometry', Point(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_location_id'], ['location.id'], use_alter=True),
    sa.ForeignKeyConstraint(['operator_id'], ['business.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['business.id'], use_alter=True),
    sa.ForeignKeyConstraint(['suboperator_id'], ['business.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_source'), 'location', ['source'], unique=False)
    op.create_index(op.f('ix_location_uid'), 'location', ['uid'], unique=False)
    op.create_index('uid', 'location', ['source'], unique=False)
    op.create_table('location_image',
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], use_alter=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True)
    )
    op.create_table('option',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Enum('string', 'date', 'datetime', 'integer', 'decimal', 'dict', 'list', name='OptionType'), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_option_key'), 'option', ['key'], unique=False)
    op.create_table('regular_hours',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('period_begin', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('related_resource',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('evse_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('types', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evse_id'], ['evse.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_resource')
    op.drop_table('regular_hours')
    op.drop_index(op.f('ix_option_key'), table_name='option')
    op.drop_table('option')
    op.drop_table('location_image')
    op.drop_index('uid', table_name='location')
    op.drop_index(op.f('ix_location_uid'), table_name='location')
    op.drop_index(op.f('ix_location_source'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_image_external_url'), table_name='image')
    op.drop_table('image')
    op.drop_table('exceptional_opening_period')
    op.drop_table('exceptional_closing_period')
    op.drop_table('evse_image')
    op.drop_index(op.f('ix_evse_uid'), table_name='evse')
    op.drop_table('evse')
    op.drop_index(op.f('ix_connector_uid'), table_name='connector')
    op.drop_table('connector')
    op.drop_index(op.f('ix_business_name'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
