"""sources

Revision ID: 9cc76344f215
Revises: 08f900d9d379
Create Date: 2024-07-20 05:30:28.819475

"""

import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

# revision identifiers, used by Alembic.
revision = '9cc76344f215'
down_revision = '08f900d9d379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'source',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('uid', sa.String(length=256), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=True),
        sa.Column('public_url', sa.String(length=4096), nullable=True),
        sa.Column('static_data_updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column('realtime_data_updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column('attribution_license', sa.Text(), nullable=True),
        sa.Column('attribution_contributor', sa.String(length=256), nullable=True),
        sa.Column('attribution_url', sa.String(length=256), nullable=True),
        sa.Column(
            'static_status', sa.Enum('DISABLED', 'ACTIVE', 'FAILED', 'PROVISIONED', name='sourcestatus'), nullable=False
        ),
        sa.Column(
            'realtime_status',
            sa.Enum('DISABLED', 'ACTIVE', 'FAILED', 'PROVISIONED', name='sourcestatus'),
            nullable=False,
        ),
        sa.Column('static_error_count', sa.Integer(), nullable=False),
        sa.Column('realtime_error_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
        mysql_charset='utf8mb4',
        mysql_collate='utf8mb4_unicode_ci',
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_uid'), ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_uid'))

    op.drop_table('source')
    # ### end Alembic commands ###
