"""extend-country-code-fix-evse-id

Revision ID: 1b51f332b7db
Revises: 9cc76344f215
Create Date: 2025-01-24 08:04:59.677988

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1b51f332b7db'
down_revision = '9cc76344f215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column(
            'country', existing_type=sa.String(length=2), type_=sa.String(length=3), existing_nullable=True
        )

    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evse_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_evse_evse_id'), ['evse_id'], unique=False)

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index('ix_source_uid')
        batch_op.create_index(batch_op.f('ix_source_uid'), ['uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_uid'))
        batch_op.create_index('ix_source_uid', ['uid'], unique=False)

    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evse_evse_id'))
        batch_op.drop_column('evse_id')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column(
            'country', existing_type=sa.String(length=3), type_=sa.String(length=2), existing_nullable=True
        )

    # ### end Alembic commands ###
