"""add foreign key indices

Revision ID: c90c108c431c
Revises: 1b51f332b7db
Create Date: 2025-11-22 06:10:11.054347

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c90c108c431c'
down_revision = '1b51f332b7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_logo_id'), ['logo_id'], unique=False)

    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_evse_id'), ['evse_id'], unique=False)

    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evse_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('evse_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evse_image_evse_id'), ['evse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evse_image_image_id'), ['image_id'], unique=False)

    with op.batch_alter_table('exceptional_closing_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exceptional_closing_period_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('exceptional_opening_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exceptional_opening_period_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('geometry_index'), postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_location_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_suboperator_id'), ['suboperator_id'], unique=False)

    with op.batch_alter_table('location_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_image_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_image_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('regular_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regular_hours_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('related_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_related_resource_evse_id'), ['evse_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_related_resource_evse_id'))

    with op.batch_alter_table('regular_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regular_hours_location_id'))

    with op.batch_alter_table('location_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_image_location_id'))
        batch_op.drop_index(batch_op.f('ix_location_image_image_id'))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_suboperator_id'))
        batch_op.drop_index(batch_op.f('ix_location_owner_id'))
        batch_op.drop_index(batch_op.f('ix_location_operator_id'))
        batch_op.create_index(batch_op.f('geometry_index'), ['geometry'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('exceptional_opening_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exceptional_opening_period_location_id'))

    with op.batch_alter_table('exceptional_closing_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exceptional_closing_period_location_id'))

    with op.batch_alter_table('evse_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evse_image_image_id'))
        batch_op.drop_index(batch_op.f('ix_evse_image_evse_id'))

    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evse_location_id'))

    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_evse_id'))

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_logo_id'))
    # ### end Alembic commands ###
