"""evse_id

Revision ID: 19a382e3e11c
Revises: 1b51f332b7db
Create Date: 2025-01-24 19:08:31.400782

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '19a382e3e11c'
down_revision = '1b51f332b7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evse_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_evse_evse_id'), ['evse_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evse_evse_id'))
        batch_op.drop_column('evse_id')

    # ### end Alembic commands ###
