"""last_modified index

Revision ID: c9deda3e7111
Revises: 5f8a2d26f35c
Create Date: 2026-01-30 16:03:39.413219

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c9deda3e7111'
down_revision = '5f8a2d26f35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evse_last_updated'), ['last_updated'], unique=False)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_last_updated'), ['last_updated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_last_updated'))

    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evse_last_updated'))
    # ### end Alembic commands ###
