"""OCPI 3.0 data model completion

Revision ID: b6cdfc8c5c34
Revises: b2c3d4e5f6a7
Create Date: 2026-02-15 11:43:57.873020

"""

import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6cdfc8c5c34'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None

old_connector_types: list[str] = [
    'CHADEMO',
    'DOMESTIC_A',
    'DOMESTIC_B',
    'DOMESTIC_C',
    'DOMESTIC_D',
    'DOMESTIC_E',
    'DOMESTIC_F',
    'DOMESTIC_G',
    'DOMESTIC_H',
    'DOMESTIC_I',
    'DOMESTIC_J',
    'DOMESTIC_K',
    'DOMESTIC_L',
    'IEC_60309_2_single_16',
    'IEC_60309_2_three_16',
    'IEC_60309_2_three_32',
    'IEC_60309_2_three_64',
    'IEC_62196_T1',
    'IEC_62196_T1_COMBO',
    'IEC_62196_T2',
    'IEC_62196_T2_COMBO',
    'IEC_62196_T3A',
    'IEC_62196_T3C',
    'PANTOGRAPH_BOTTOM_UP',
    'PANTOGRAPH_TOP_DOWN',
    'TESLA_R',
    'TESLA_S',
]

new_connector_types: list[str] = old_connector_types + [
    'MCS',
    'SAE_J3400',
    'NEMA_5_20',
    'NEMA_6_30',
    'NEMA_6_50',
    'NEMA_10_30',
    'NEMA_10_50',
    'NEMA_14_30',
    'NEMA_14_50',
    'GBT_AC',
    'GBT_DC',
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Extend connectortype enum with new values for PostgreSQL
    if op.get_bind().engine.name == 'postgresql':
        op.execute('ALTER TYPE connectortype RENAME TO _connectortype')
        sa.Enum(*new_connector_types, name='connectortype').create(op.get_bind())
        op.execute(
            'ALTER TABLE connector ALTER COLUMN standard type connectortype using standard::text::connectortype;'
        )
        sa.Enum(*old_connector_types, name='_connectortype').drop(op.get_bind())

    op.create_table(
        'charging_station',
        sa.Column('location_id', sa.BigInteger(), nullable=False),
        sa.Column('uid', sa.String(length=36), nullable=False),
        sa.Column('capabilities', sa.Integer(), nullable=True),
        sa.Column('floor_level', sa.String(length=16), nullable=True),
        sa.Column('physical_reference', sa.String(length=255), nullable=True),
        sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('go_live_date', sa.Date(), nullable=True),
        sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=True),
        sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column('directions', sa.Text(), nullable=True),
        sa.Column('max_power_unit', sa.Enum('W', 'KW', 'A', name='chargingrateunit'), nullable=True),
        sa.Column('max_power_value', sa.Float(), nullable=True),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['location_id'], ['location.id'], name=op.f('fk_charging_station_location_id'), use_alter=True
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_charging_station')),
        mysql_charset='utf8mb4',
        mysql_collate='utf8mb4_unicode_ci',
    )
    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charging_station_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_station_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_station_uid'), ['uid'], unique=False)

    op.create_table(
        'charging_station_image',
        sa.Column('charging_station_id', sa.BigInteger(), nullable=False),
        sa.Column('image_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['charging_station_id'], ['charging_station.id'], name=op.f('fk_charging_station_image_charging_station_id')
        ),
        sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('fk_charging_station_image_image_id')),
        sa.PrimaryKeyConstraint('charging_station_id', 'image_id', name=op.f('pk_charging_station_image')),
    )
    with op.batch_alter_table('charging_station_image', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_charging_station_image_charging_station_id'), ['charging_station_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_charging_station_image_image_id'), ['image_id'], unique=False)

    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.alter_column('last_updated', existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)

    # Create PresenceStatus enum type explicitly (add_column does not auto-create enum types in PostgreSQL)
    presence_status_enum = postgresql.ENUM('PRESENT', 'PLANNED', 'REMOVED', name='PresenceStatus', create_type=False)
    presence_status_enum.create(op.get_bind(), checkfirst=True)

    # Phase 1: Add new evse columns (charging_station_id as nullable for now, presence with server_default)
    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charging_station_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('presence', presence_status_enum, server_default='PRESENT', nullable=False))
        batch_op.add_column(
            sa.Column('status_last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column('calibration_info_url', sa.String(length=255), nullable=True))

    # Add help_phone to location early so we can populate it from evse.phone
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('help_phone', sa.String(length=255), nullable=True))

    # Data migration: Create one charging_station per location and link evses
    op.execute(
        sa.text("""
        INSERT INTO charging_station (location_id, uid, last_updated, created, modified)
        SELECT id, uid, last_updated, NOW(), NOW()
        FROM location
    """)
    )
    op.execute(
        sa.text("""
        UPDATE evse
        SET charging_station_id = cs.id
        FROM charging_station cs
        WHERE evse.location_id = cs.location_id
    """)
    )

    # Data migration: Move evse.phone to location.help_phone
    op.execute(
        sa.text("""
        UPDATE location
        SET help_phone = sub.phone
        FROM (
            SELECT DISTINCT ON (location_id) location_id, phone
            FROM evse
            WHERE phone IS NOT NULL
            ORDER BY location_id, id
        ) sub
        WHERE location.id = sub.location_id
    """)
    )

    # Phase 2: Make charging_station_id NOT NULL, drop old columns and constraints
    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.alter_column('charging_station_id', nullable=False)
        batch_op.alter_column('presence', server_default=None)
        batch_op.alter_column('last_updated', existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
        batch_op.drop_index(batch_op.f('ix_evse_location_id'))
        batch_op.create_index(batch_op.f('ix_evse_charging_station_id'), ['charging_station_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_evse_location_id'), type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_evse_charging_station_id'),
            'charging_station',
            ['charging_station_id'],
            ['id'],
            use_alter=True,
        )
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')
        batch_op.drop_column('directions')
        batch_op.drop_column('floor_level')
        batch_op.drop_column('location_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('capabilities')
        batch_op.drop_column('parking_floor_level')
        batch_op.drop_column('parking_uid')
        batch_op.drop_column('parking_spot_number')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charging_when_closed', sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column('max_power_unit', sa.Enum('W', 'KW', 'A', name='chargingrateunit'), nullable=True)
        )
        batch_op.add_column(sa.Column('max_power_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy_mix', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('related_locations', sa.Text(), nullable=True))
        batch_op.alter_column('last_updated', existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)

    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('fk_charging_station_location_id'), 'location', ['location_id'], ['id'], use_alter=True
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_charging_station_location_id'), type_='foreignkey')

    # Drop location columns except help_phone (needed for data migration to evse.phone)
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('last_updated', existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
        batch_op.drop_column('related_locations')
        batch_op.drop_column('energy_mix')
        batch_op.drop_column('max_power_value')
        batch_op.drop_column('max_power_unit')
        batch_op.drop_column('charging_when_closed')

    # Phase 1: Add old evse columns back (location_id as nullable for now)
    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('parking_spot_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
        )
        batch_op.add_column(sa.Column('parking_uid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(
            sa.Column('parking_floor_level', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
        )
        batch_op.add_column(sa.Column('capabilities', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('floor_level', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('directions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.NUMERIC(precision=9, scale=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lon', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))

    # Data migration: Assign evses back to their location via charging_station
    op.execute(
        sa.text("""
        UPDATE evse
        SET location_id = cs.location_id
        FROM charging_station cs
        WHERE evse.charging_station_id = cs.id
    """)
    )

    # Data migration: Move location.help_phone back to evse.phone
    op.execute(
        sa.text("""
        UPDATE evse
        SET phone = l.help_phone
        FROM location l
        WHERE evse.location_id = l.id
    """)
    )

    # Drop help_phone now that it has been migrated to evse.phone
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('help_phone')

    # Phase 2: Make location_id NOT NULL, drop charging_station-related columns and constraints
    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.alter_column('location_id', nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_evse_charging_station_id'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_evse_location_id'), 'location', ['location_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_evse_charging_station_id'))
        batch_op.create_index(batch_op.f('ix_evse_location_id'), ['location_id'], unique=False)
        batch_op.alter_column('last_updated', existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
        batch_op.drop_column('calibration_info_url')
        batch_op.drop_column('status_last_updated')
        batch_op.drop_column('presence')
        batch_op.drop_column('charging_station_id')

    # Drop PresenceStatus enum type after the column is removed
    presence_status_enum = postgresql.ENUM('PRESENT', 'PLANNED', 'REMOVED', name='PresenceStatus', create_type=False)
    presence_status_enum.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.alter_column('last_updated', existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)

    with op.batch_alter_table('charging_station_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charging_station_image_image_id'))
        batch_op.drop_index(batch_op.f('ix_charging_station_image_charging_station_id'))

    op.drop_table('charging_station_image')
    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charging_station_uid'))
        batch_op.drop_index(batch_op.f('ix_charging_station_location_id'))
        batch_op.drop_index(batch_op.f('ix_charging_station_last_updated'))

    op.drop_table('charging_station')

    # Drop chargingrateunit enum type after all columns/tables using it are removed
    if op.get_bind().engine.name == 'postgresql':
        sa.Enum('W', 'KW', 'A', name='chargingrateunit').drop(op.get_bind(), checkfirst=True)

    # Revert connectortype enum to old values for PostgreSQL
    if op.get_bind().engine.name == 'postgresql':
        op.execute('ALTER TYPE connectortype RENAME TO _connectortype')
        sa.Enum(*old_connector_types, name='connectortype').create(op.get_bind())
        op.execute(
            'ALTER TABLE connector ALTER COLUMN standard type connectortype using standard::text::connectortype;'
        )
        sa.Enum(*new_connector_types, name='_connectortype').drop(op.get_bind())
    # ### end Alembic commands ###
