"""tariffs

Revision ID: 1c7cd6b0e6c6
Revises: 3e82cc1bc169
Create Date: 2026-03-22 15:14:20.891269

"""

import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

# revision identifiers, used by Alembic.
revision = '1c7cd6b0e6c6'
down_revision = '3e82cc1bc169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tariff',
        sa.Column('uid', sa.String(length=64), nullable=False),
        sa.Column('source', sa.String(length=64), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('elements', sa.Text(), nullable=False),
        sa.Column('tariff_alt_url', sa.String(length=255), nullable=True),
        sa.Column('tariff_alt_text', sa.Text(), nullable=True),
        sa.Column('min_price', sa.Text(), nullable=True),
        sa.Column('max_price', sa.Text(), nullable=True),
        sa.Column('energy_mix', sa.Text(), nullable=True),
        sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff')),
    )
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_uid'), ['uid'], unique=False)
        batch_op.create_index('ix_tariff_uid_source', ['uid', 'source'], unique=False)

    op.create_table(
        'tariff_association',
        sa.Column('tariff_id', sa.BigInteger(), nullable=False),
        sa.Column('uid', sa.String(length=64), nullable=False),
        sa.Column('source', sa.String(length=64), nullable=False),
        sa.Column('audience', sa.Enum('AD_HOC_PAYMENT', 'EMSP_CONTRACT', name='tariffaudience'), nullable=True),
        sa.Column('start_date_time', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column('modified', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['tariff_id'], ['tariff.id'], name=op.f('fk_tariff_association_tariff_id'), use_alter=True
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff_association')),
    )
    with op.batch_alter_table('tariff_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_association_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_association_tariff_id'), ['tariff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_association_uid'), ['uid'], unique=False)
        batch_op.create_index('ix_tariff_association_uid_source', ['uid', 'source'], unique=False)

    op.create_table(
        'connector_tariff_association',
        sa.Column('connector_id', sa.BigInteger(), nullable=False),
        sa.Column('tariff_association_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['connector_id'], ['connector.id'], name=op.f('fk_connector_tariff_association_connector_id')
        ),
        sa.ForeignKeyConstraint(
            ['tariff_association_id'],
            ['tariff_association.id'],
            name=op.f('fk_connector_tariff_association_tariff_association_id'),
        ),
        sa.PrimaryKeyConstraint('connector_id', 'tariff_association_id', name=op.f('pk_connector_tariff_association')),
    )
    with op.batch_alter_table('connector_tariff_association', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_connector_tariff_association_connector_id'), ['connector_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_connector_tariff_association_tariff_association_id'), ['tariff_association_id'], unique=False
        )

    op.create_table(
        'evse_tariff_association',
        sa.Column('evse_id', sa.BigInteger(), nullable=False),
        sa.Column('tariff_association_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['evse_id'], ['evse.id'], name=op.f('fk_evse_tariff_association_evse_id')),
        sa.ForeignKeyConstraint(
            ['tariff_association_id'],
            ['tariff_association.id'],
            name=op.f('fk_evse_tariff_association_tariff_association_id'),
        ),
        sa.PrimaryKeyConstraint('evse_id', 'tariff_association_id', name=op.f('pk_evse_tariff_association')),
    )
    with op.batch_alter_table('evse_tariff_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evse_tariff_association_evse_id'), ['evse_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_evse_tariff_association_tariff_association_id'), ['tariff_association_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evse_tariff_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evse_tariff_association_tariff_association_id'))
        batch_op.drop_index(batch_op.f('ix_evse_tariff_association_evse_id'))

    op.drop_table('evse_tariff_association')
    with op.batch_alter_table('connector_tariff_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_tariff_association_tariff_association_id'))
        batch_op.drop_index(batch_op.f('ix_connector_tariff_association_connector_id'))

    op.drop_table('connector_tariff_association')
    with op.batch_alter_table('tariff_association', schema=None) as batch_op:
        batch_op.drop_index('ix_tariff_association_uid_source')
        batch_op.drop_index(batch_op.f('ix_tariff_association_uid'))
        batch_op.drop_index(batch_op.f('ix_tariff_association_tariff_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_association_source'))

    op.drop_table('tariff_association')
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.drop_index('ix_tariff_uid_source')
        batch_op.drop_index(batch_op.f('ix_tariff_uid'))
        batch_op.drop_index(batch_op.f('ix_tariff_source'))

    op.drop_table('tariff')
    # ### end Alembic commands ###
