"""additional datex fields

Revision ID: 3e82cc1bc169
Revises: 61592620e09b
Create Date: 2026-03-11 05:47:31.139739

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e82cc1bc169'
down_revision = '61592620e09b'
branch_labels = None
depends_on = None

servicetype_enum = postgresql.ENUM('PHYSICAL_ATTENDANCE', 'UNATTENDED', name='servicetype')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    servicetype_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emobility_uid', sa.String(length=255), nullable=True))

    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('service_type', sa.Enum('PHYSICAL_ATTENDANCE', 'UNATTENDED', name='servicetype'), nullable=True)
        )
        batch_op.add_column(sa.Column('user_interface_languages', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.drop_column('user_interface_languages')
        batch_op.drop_column('service_type')

    servicetype_enum.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('emobility_uid')

    # ### end Alembic commands ###
