"""evse status index

Revision ID: 78708f842662
Revises: c9deda3e7111
Create Date: 2026-01-30 18:01:39.164138

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '78708f842662'
down_revision = 'c9deda3e7111'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evse_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evse_status'))
    # ### end Alembic commands ###
