"""official_region_code

Revision ID: 61592620e09b
Revises: b2c3d4e5f6a7
Create Date: 2026-02-01 08:07:44.582677

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '61592620e09b'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_region_code', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_country_official_region_code', ['country', 'official_region_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index('ix_country_official_region_code')
        batch_op.drop_column('official_region_code')

    # ### end Alembic commands ###
