"""add location index back

Revision ID: 5f8a2d26f35c
Revises: c90c108c431c
Create Date: 2026-01-25 11:27:29.857379

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '5f8a2d26f35c'
down_revision = 'c90c108c431c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uid'))
        batch_op.create_index('geometry_index', ['geometry'], unique=False, postgresql_using='gist')
        batch_op.create_index('uid_source', ['uid', 'source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index('uid_source')
        batch_op.drop_index('geometry_index', postgresql_using='gist')
        batch_op.create_index(batch_op.f('uid'), ['source'], unique=False)

    # ### end Alembic commands ###
