"""more datex fields

Revision ID: 76e048ecbc17
Revises: 1c7cd6b0e6c6
Create Date: 2026-04-10 06:25:20.766225

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '76e048ecbc17'
down_revision = '1c7cd6b0e6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking_spaces', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_in_person_support', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('facilities', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('facility_description', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('parking_spaces', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('tariff_association', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('fk_tariff_association_tariff_id'), 'tariff', ['tariff_id'], ['id'], use_alter=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff_association', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tariff_association_tariff_id'), type_='foreignkey')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('parking_spaces')
        batch_op.drop_column('facility_description')
        batch_op.drop_column('facilities')
        batch_op.drop_column('has_in_person_support')

    with op.batch_alter_table('charging_station', schema=None) as batch_op:
        batch_op.drop_column('parking_spaces')

    # ### end Alembic commands ###
