"""
Copyright 2026 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from enum import Enum


class PictogramEnum(Enum):
    BLANKVOID = 'blankVoid'
    BRIDGECLOSED = 'bridgeClosed'
    CARPARKFULL = 'carParkFull'
    CARPARKSPACESAVAILABLE = 'carParkSpacesAvailable'
    CORRIDORFOREMERGENCYVEHICLEACCESS = 'corridorForEmergencyVehicleAccess'
    CURVEARROWTOLEFT = 'curveArrowToLeft'
    CURVEARROWTORIGHT = 'curveArrowToRight'
    DANGEROFFIRE = 'dangerOfFire'
    DOUBLEEXITTOLEFT = 'doubleExitToLeft'
    DOUBLEEXITTORIGHT = 'doubleExitToRight'
    ENDOFADVISORYSPEED = 'endOfAdvisorySpeed'
    FASTENCHILDRENSSEATBELTS = 'fastenChildrensSeatBelts'
    FASTENYOURSEATBELT = 'fastenYourSeatBelt'
    FIRE = 'fire'
    FOOTBALLMATCH = 'footballMatch'
    HARDSHOULDERNOTRUNNING = 'hardShoulderNotRunning'
    HARDSHOULDERRUNNING = 'hardShoulderRunning'
    HORIZONTALDIVERSIONTOLEFT = 'horizontalDiversionToLeft'
    HORIZONTALDIVERSIONTORIGHT = 'horizontalDiversionToRight'
    KEEPASAFEDISTANCE = 'keepASafeDistance'
    KEEPLEFT = 'keepLeft'
    KEEPRIGHT = 'keepRight'
    LANE1CLOSEDOF2 = 'lane1ClosedOf2'
    LANE2CLOSEDOF2 = 'lane2ClosedOf2'
    LANE1CLOSEDOF3 = 'lane1ClosedOf3'
    LANE3CLOSEDOF3 = 'lane3ClosedOf3'
    LANES1AND2CLOSEDOF3 = 'lanes1And2ClosedOf3'
    LANES2AND3CLOSEDOF3 = 'lanes2And3ClosedOf3'
    LANE1CLOSEDOF4 = 'lane1ClosedOf4'
    LANE4CLOSEDOF4 = 'lane4ClosedOf4'
    LANES1AND2CLOSEDOF4 = 'lanes1And2ClosedOf4'
    LANES3AND4CLOSEDOF4 = 'lanes3And4ClosedOf4'
    LANES1AND2AND3CLOSEDOF4 = 'lanes1And2And3ClosedOf4'
    LANES2AND3AND4CLOSEDOF4 = 'lanes2And3And4ClosedOf4'
    LEFTHANDLANECLOSED = 'leftHandLaneClosed'
    NARROWLANESAHEAD = 'narrowLanesAhead'
    OBLIQUEARROWTOLEFT = 'obliqueArrowToLeft'
    OBLIQUEARROWTORIGHT = 'obliqueArrowToRight'
    POLLUTIONORSMOGALERT = 'pollutionOrSmogAlert'
    RIGHTHANDLANECLOSED = 'rightHandLaneClosed'
    SINGLEEXITTOLEFT = 'singleExitToLeft'
    SINGLEEXITTORIGHT = 'singleExitToRight'
    SMOKE = 'smoke'
    SNOWPLOUGHINACTION = 'snowPloughInAction'
    SPEEDCAMERASINACTION = 'speedCamerasInAction'
    STRAIGHTVERTICALARROW = 'straightVerticalArrow'
    TRAFFICDEVIATEDTOOPPOSITECARRIAGEWAYAHEAD = 'trafficDeviatedToOppositeCarriagewayAhead'
    TRAFFICPARTIALLYDEVIATEDTOOPPOSITECARRIAGEWAYAHEAD = 'trafficPartiallyDeviatedToOppositeCarriagewayAhead'
    TUNNELCLOSED = 'tunnelClosed'
    VERTICALDIVERSION = 'verticalDiversion'
    OTHER = 'other'
    EXTENDEDG = 'extendedG'
