"""
Copyright 2026 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from enum import Enum


class PoorEnvironmentTypeEnum(Enum):
    BADWEATHER = 'badWeather'
    BLIZZARD = 'blizzard'
    BLOWINGDUST = 'blowingDust'
    BLOWINGSNOW = 'blowingSnow'
    CROSSWINDS = 'crosswinds'
    DAMAGINGHAIL = 'damagingHail'
    DENSEFOG = 'denseFog'
    ECLIPSE = 'eclipse'
    EXTREMECOLD = 'extremeCold'
    EXTREMEHEAT = 'extremeHeat'
    FOG = 'fog'
    FREEZINGFOG = 'freezingFog'
    FROST = 'frost'
    GALES = 'gales'
    GUSTYWINDS = 'gustyWinds'
    HAIL = 'hail'
    HEAVYFROST = 'heavyFrost'
    HEAVYRAIN = 'heavyRain'
    HEAVYSNOWFALL = 'heavySnowfall'
    HURRICANEFORCEWINDS = 'hurricaneForceWinds'
    LOWSUNGLARE = 'lowSunGlare'
    MODERATEFOG = 'moderateFog'
    NEARBYFIRE = 'nearbyFire'
    NEARBYFLOODING = 'nearbyFlooding'
    OZONEPOLLUTION = 'ozonePollution'
    POLLUTION = 'pollution'
    PATCHYFOG = 'patchyFog'
    PRECIPITATIONINTHEAREA = 'precipitationInTheArea'
    RAIN = 'rain'
    RAINCHANGINGTOSNOW = 'rainChangingToSnow'
    SANDSTORMS = 'sandStorms'
    SEVEREEXHAUSTPOLLUTION = 'severeExhaustPollution'
    SEVERESMOG = 'severeSmog'
    SHOWERS = 'showers'
    SLEET = 'sleet'
    SMOGALERT = 'smogAlert'
    SMOKEHAZARD = 'smokeHazard'
    SNOWCHANGINGTORAIN = 'snowChangingToRain'
    SNOWFALL = 'snowfall'
    SPRAYHAZARD = 'sprayHazard'
    STORMFORCEWINDS = 'stormForceWinds'
    STRONGGUSTSOFWIND = 'strongGustsOfWind'
    STRONGWINDS = 'strongWinds'
    SWARMSOFINSECTS = 'swarmsOfInsects'
    TEMPERATUREFALLING = 'temperatureFalling'
    THUNDERSTORMS = 'thunderstorms'
    TORNADOES = 'tornadoes'
    VERYSTRONGGUSTSOFWIND = 'veryStrongGustsOfWind'
    VISIBILITYREDUCED = 'visibilityReduced'
    WHITEOUT = 'whiteOut'
    WINTERSTORM = 'winterStorm'
    EXTENDEDG = 'extendedG'
