"""
Giro-e OCPI
Copyright (c) 2022, binary butterfly GmbH
All rights reserved.
"""

from enum import Enum


class EventSource(Enum):
    OCPI = 'OCPI'
    SERVER = 'SERVER'
    ORM = 'ORM'


class EventType(Enum):
    CDR_CREATED = 'CDR_CREATED'
    CDR_UPDATED = 'CDR_UPDATED'
    CDR_DELETED = 'CDR_DELETED'
    CONNECTOR_CREATED = 'CONNECTOR_CREATED'
    CONNECTOR_UPDATED = 'CONNECTOR_UPDATED'
    CONNECTOR_DELETED = 'CONNECTOR_DELETED'
    CREDENTIALS_CREATED = 'CREDENTIALS_CREATED'
    CREDENTIALS_UPDATED = 'CREDENTIALS_UPDATED'
    CREDENTIALS_DELETED = 'CREDENTIALS_DELETED'
    EVSE_CREATED = 'EVSE_CREATED'
    EVSE_UPDATED = 'EVSE_UPDATED'
    EVSE_DELETED = 'EVSE_DELETED'
    EVSE_STATUS_UPDATED = 'EVSE_STATUS_UPDATED'
    IMAGE_CREATED = 'IMAGE_CREATED'
    IMAGE_UPDATED = 'IMAGE_UPDATED'
    IMAGE_DELETED = 'IMAGE_DELETED'
    LOCATION_CREATED = 'LOCATION_CREATED'
    LOCATION_UPDATED = 'LOCATION_UPDATED'
    LOCATION_DELETED = 'LOCATION_DELETED'
    TARIFF_CREATED = 'TARIFF_CREATED'
    TARIFF_UPDATED = 'TARIFF_UPDATED'
    TARIFF_DELETED = 'TARIFF_DELETED'
    SESSION_CREATED = 'SESSION_CREATED'
    SESSION_UPDATED = 'SESSION_UPDATED'
    SESSION_DELETED = 'SESSION_DELETED'
    TOKEN_CREATED = 'TOKEN_CREATED'
    TOKEN_UPDATED = 'TOKEN_UPDATED'
    TOKEN_DELETED = 'TOKEN_DELETED'
