"""
Copyright 2026 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from enum import Enum


class VehicleTypeEnum(Enum):
    AGRICULTURALVEHICLE = 'agriculturalVehicle'
    ANYVEHICLE = 'anyVehicle'
    ARTICULATEDBUS = 'articulatedBus'
    ARTICULATEDTROLLEYBUS = 'articulatedTrolleyBus'
    ARTICULATEDVEHICLE = 'articulatedVehicle'
    BICYCLE = 'bicycle'
    BUS = 'bus'
    CAR = 'car'
    CARAVAN = 'caravan'
    CARORLIGHTVEHICLE = 'carOrLightVehicle'
    CARWITHCARAVAN = 'carWithCaravan'
    CARWITHTRAILER = 'carWithTrailer'
    CONSTRUCTIONORMAINTENANCEVEHICLE = 'constructionOrMaintenanceVehicle'
    FOURWHEELDRIVE = 'fourWheelDrive'
    HEAVYGOODSVEHICLE = 'heavyGoodsVehicle'
    HEAVYGOODSVEHICLEWITHTRAILER = 'heavyGoodsVehicleWithTrailer'
    HEAVYDUTYTRANSPORTER = 'heavyDutyTransporter'
    HEAVYVEHICLE = 'heavyVehicle'
    HIGHSIDEDVEHICLE = 'highSidedVehicle'
    LIGHTCOMMERCIALVEHICLE = 'lightCommercialVehicle'
    LARGECAR = 'largeCar'
    LARGEGOODSVEHICLE = 'largeGoodsVehicle'
    LIGHTCOMMERCIALVEHICLEWITHTRAILER = 'lightCommercialVehicleWithTrailer'
    LONGHEAVYLORRY = 'longHeavyLorry'
    LORRY = 'lorry'
    METRO = 'metro'
    MINIBUS = 'minibus'
    MOPED = 'moped'
    MOTORCYCLE = 'motorcycle'
    MOTORCYCLEWITHSIDECAR = 'motorcycleWithSideCar'
    MOTORHOME = 'motorhome'
    MOTORSCOOTER = 'motorscooter'
    PASSENGERCAR = 'passengerCar'
    SMALLCAR = 'smallCar'
    TANKER = 'tanker'
    THREEWHEELEDVEHICLE = 'threeWheeledVehicle'
    TRAILER = 'trailer'
    TRAM = 'tram'
    TROLLEYBUS = 'trolleyBus'
    TWOWHEELEDVEHICLE = 'twoWheeledVehicle'
    VAN = 'van'
    VEHICLEWITHCARAVAN = 'vehicleWithCaravan'
    VEHICLEWITHCATALYTICCONVERTER = 'vehicleWithCatalyticConverter'
    VEHICLEWITHOUTCATALYTICCONVERTER = 'vehicleWithoutCatalyticConverter'
    VEHICLEWITHTRAILER = 'vehicleWithTrailer'
    WITHEVENNUMBEREDREGISTRATIONPLATES = 'withEvenNumberedRegistrationPlates'
    WITHODDNUMBEREDREGISTRATIONPLATES = 'withOddNumberedRegistrationPlates'
    UNKNOWN = 'unknown'
    OTHER = 'other'
    EXTENDEDG = 'extendedG'
