"""
Copyright 2026 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from enum import Enum


class PublicEventTypeEnum(Enum):
    AGRICULTURALSHOW = 'agriculturalShow'
    AIRSHOW = 'airShow'
    ARTEVENT = 'artEvent'
    ATHLETICSMEETING = 'athleticsMeeting'
    COMMERCIALEVENT = 'commercialEvent'
    CULTURALEVENT = 'culturalEvent'
    BALLGAME = 'ballGame'
    BASEBALLGAME = 'baseballGame'
    BASKETBALLGAME = 'basketballGame'
    BEERFESTIVAL = 'beerFestival'
    BICYCLERACE = 'bicycleRace'
    BOATRACE = 'boatRace'
    BOATSHOW = 'boatShow'
    BOXINGTOURNAMENT = 'boxingTournament'
    BULLFIGHT = 'bullFight'
    CEREMONIALEVENT = 'ceremonialEvent'
    CONCERT = 'concert'
    CRICKETMATCH = 'cricketMatch'
    EXHIBITION = 'exhibition'
    FAIR = 'fair'
    FESTIVAL = 'festival'
    FILMFESTIVAL = 'filmFestival'
    FILMTVMAKING = 'filmTVMaking'
    FIREWORKDISPLAY = 'fireworkDisplay'
    FLOWEREVENT = 'flowerEvent'
    FOODFESTIVAL = 'foodFestival'
    FOOTBALLMATCH = 'footballMatch'
    FUNFAIR = 'funfair'
    GARDENINGORFLOWERSHOW = 'gardeningOrFlowerShow'
    GOLFTOURNAMENT = 'golfTournament'
    HOCKEYGAME = 'hockeyGame'
    HORSERACEMEETING = 'horseRaceMeeting'
    INTERNATIONALSPORTSMEETING = 'internationalSportsMeeting'
    MAJOREVENT = 'majorEvent'
    MARATHON = 'marathon'
    MARKET = 'market'
    MATCH = 'match'
    MOTORSHOW = 'motorShow'
    MOTORSPORTRACEMEETING = 'motorSportRaceMeeting'
    OPENAIRCONCERT = 'openAirConcert'
    PARADE = 'parade'
    PROCESSION = 'procession'
    RACEMEETING = 'raceMeeting'
    RUGBYMATCH = 'rugbyMatch'
    SEVERALMAJOREVENTS = 'severalMajorEvents'
    SHOW = 'show'
    SHOWJUMPING = 'showJumping'
    SOUNDANDLIGHTSHOW = 'soundAndLightShow'
    SPORTSMEETING = 'sportsMeeting'
    STATEOCCASION = 'stateOccasion'
    STREETFESTIVAL = 'streetFestival'
    TENNISTOURNAMENT = 'tennisTournament'
    THEATRICALEVENT = 'theatricalEvent'
    TOURNAMENT = 'tournament'
    TRADEFAIR = 'tradeFair'
    WATERSPORTSMEETING = 'waterSportsMeeting'
    WINEFESTIVAL = 'wineFestival'
    WINTERSPORTSMEETING = 'winterSportsMeeting'
    UNKNOWN = 'unknown'
    OTHER = 'other'
    EXTENDEDG = 'extendedG'
