"""
Copyright 2026 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from enum import Enum


class SubdivisionTypeEnum(Enum):
    ADMINISTRATIVEATOLL = 'administrativeAtoll'
    ADMINISTRATIVEREGION = 'administrativeRegion'
    ADMINISTRATIVETERRITORY = 'administrativeTerritory'
    ARCTICREGION = 'arcticRegion'
    AUTONOMOUSCITY = 'autonomousCity'
    AUTONOMOUSCITYINNORTHAFRICA = 'autonomousCityInNorthAfrica'
    AUTONOMOUSCOMMUNITY = 'autonomousCommunity'
    AUTONOMOUSDISTRICT = 'autonomousDistrict'
    AUTONOMOUSPROVINCE = 'autonomousProvince'
    AUTONOMOUSREGION = 'autonomousRegion'
    CANTON = 'canton'
    CAPITALCITY = 'capitalCity'
    CITY = 'city'
    CITYMUNICIPALITY = 'cityMunicipality'
    CITYOFCOUNTYRIGHT = 'cityOfCountyRight'
    COMMUNE = 'commune'
    COUNCILAREA = 'councilArea'
    COUNTY = 'county'
    COUNTRY = 'country'
    DEPARTMENT = 'department'
    DEPENDENCY = 'dependency'
    DISTRICT = 'district'
    DISTRICTMUNICIPALITY = 'districtMunicipality'
    DISTRICTWITHSPECIALSTATUS = 'districtWithSpecialStatus'
    ENTITY = 'entity'
    GEOGRAPHICALENTITY = 'geographicalEntity'
    GOVERNORATE = 'governorate'
    LAENDER = 'laender'
    LOCALCOUNCIL = 'localCouncil'
    LONDONBOROUGH = 'londonBorough'
    METROPOLITANAREA = 'metropolitanArea'
    METROPOLITANDEPARTMENT = 'metropolitanDepartment'
    METROPOLITANDISTRICT = 'metropolitanDistrict'
    METROPOLITANREGION = 'metropolitanRegion'
    MUNICIPALITY = 'municipality'
    OVERSEASDEPARTMENT = 'overseasDepartment'
    OVERSEASREGION = 'overseasRegion'
    OVERSEASTERRITORIALCOLLECTIVITY = 'overseasTerritorialCollectivity'
    PARISH = 'parish'
    PROVINCE = 'province'
    QUARTER = 'quarter'
    REGION = 'region'
    REPUBLIC = 'republic'
    REPUBLICANCITY = 'republicanCity'
    SELFGOVERNEDPART = 'selfGovernedPart'
    SPECIALMUNICIPALITY = 'specialMunicipality'
    STATE = 'state'
    TERRITORIALUNIT = 'territorialUnit'
    TERRITORY = 'territory'
    TWOTIERCOUNTY = 'twoTierCounty'
    UNITARYAUTHORITY = 'unitaryAuthority'
    WARD = 'ward'
    OTHER = 'other'
    EXTENDEDG = 'extendedG'
