name: build & publish Docker image

on:
  release:
    types:
      - published
  pull_request:
    branches: [ "main" ]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: log into the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: build and push Docker release image
      uses: docker/build-push-action@v6
      if: github.ref_type == 'tag'
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: Dockerfile.prod

    - name: build and push Docker branch image
      uses: docker/build-push-action@v6
      if: github.ref_type == 'branch'
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.head_ref }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: Dockerfile.prod
